{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-matlib
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/matlib_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/matlib/matlib_{{ version }}.tar.gz
  sha256: 6c130ed6e435dc33d070f70cdc1fa932bd45122024cf2bc8faa4a0663bb971b1

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car
    - r-dplyr
    - r-knitr
    - r-rgl
    - r-rmarkdown
    - r-rstudioapi
    - r-xtable
  run:
    - r-base
    - r-mass
    - r-car
    - r-dplyr
    - r-knitr
    - r-rgl
    - r-rmarkdown
    - r-rstudioapi
    - r-xtable

test:
  commands:
    - $R -e "library('matlib')"           # [not win]
    - "\"%R%\" -e \"library('matlib')\""  # [win]

about:
  home: https://github.com/friendly/matlib
  license: GPL-2.0-or-later
  summary: A collection of matrix functions for teaching and learning matrix linear algebra as used in multivariate statistical methods. These functions are mainly for tutorial purposes in learning matrix algebra ideas using R. In some cases, functions are provided for concepts available elsewhere in R, but where the function
    call or name is not obvious. In other cases, functions are provided to show or demonstrate an algorithm. In addition, a collection of functions are provided for drawing vector diagrams in 2D and 3D.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
