appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: A/XDKukJk4ByC1zZKRTkDUOjW+WGtdHEARYPUWlR/pC+fTqE3qPYczaPceet6YyXjW0xYhmJvofrn1SjYWF48O493fCdmO87HoyZcbeQnaeKv6oMIgYja/NRMvMB+mCV2s7vF7mYUZe7KA8srqbLkJlbmQiRJ8J0tJoe1osXJMTLf/Oq/GRyfPchwIXG6XWI7jEB3wGqA5IF1mjldAG/2U3D/gyp1pokNxoFA1WTC68ytt7m17yXkZdgzUmx5yxByo/SUL52yFPXPJ91WfBB5AzQDACZNxWIQSfMJEqQcaHP9r6DrRfls+3/RPXcruUXSsaM3YFb+5HyxNQ6VD/Ab3eNdzQw7FmysbpFkvuXhi7HJQrLk2JSaivKTfXDq5goXPeAFZwegQj0oXcRs97LjX2DT3XTL0TjhKxahLY++2L0NLreySWcRchZj1aDgh/QtElrmlzmhSzgnmQlMN2SLtMGHpW5W+LhCwyh+ZIkxAfy5zL+4A5Snhlk6P3ktypAV2tXTB8SJ0gE893qMJaP0CwIB4p1wtX9qQacKJ4yW7gOW8szh7AhnZywdBoN1k7NheCH6NWcR2ILkHnp6aamfJqJvzLGzRUxlrkSQh3LDi3baClsumohU1xTeOA4TlYjImcu1/iHaOBfHcbyqQSsK4Zxw1Nl/IiP/Gkxu7iRjQ4=
